# Generated by Django 5.2.5 on 2025-08-09 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('ph_no', models.IntegerField()),
                ('about', models.TextField()),
                ('location', models.TextField()),
                ('image', models.ImageField(blank=True, default='https://www.bing.com/images/search?q=default%20profile%20picture&FORM=IQFRBA&id=5ECB59CC77F50C6345FA39079C91A16254A94879', null=True, upload_to='farmer_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('location', models.TextField()),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm', to='farmer.farmer')),
            ],
        ),
    ]
