# Generated by Django 5.2.5 on 2025-08-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_rename_user_id_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountcode',
            name='expires_at',
        ),
    ]
