# Generated by Django 5.2.5 on 2025-08-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likereview',
            old_name='review_id',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='likereview',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='producr_id',
            new_name='producr',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='unlikereview',
            old_name='review_id',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='unlikereview',
            old_name='user_id',
            new_name='user',
        ),
    ]
