# Generated by Django 5.2.5 on 2025-08-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_review_id_likereview_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='producr',
            new_name='product',
        ),
    ]
